# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ff644625adc47ad17ab6a0b653c1151479b775dd7f542d51a8efe1329ac9be1d158badbea6660f654c073846a44a5afb5d64d3504a8102be3f4a4b7db75876d4

test:
  secret_key_base: f9bd1fc1ab3b07aee92ee08a14ecee658a188004f353ba24c4bb3bd3dc56289f37dd3f2d45ef0e85e8189440e2897115463e883d4286f1d060a5e497ddd9723d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
